//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONARIO()
        {
            this.PRODUTOes = new HashSet<PRODUTO>();
            this.VENDAs = new HashSet<VENDA>();
        }
    
        public int COD_FUNCIONARIO { get; set; }
        public string NOME { get; set; }
        public string CPF { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public string EMAIL { get; set; }
        public string ENDERECO { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string TIPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO> PRODUTOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENDA> VENDAs { get; set; }
    }
}
