//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDA
    {
        public int COD_VENDA { get; set; }
        public int COD_FUNCIONARIO { get; set; }
        public int COD_PRODUTO { get; set; }
        public int NUM_NF { get; set; }
        public System.DateTime DATA { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
